sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_98f85f8775b8_key -iv $encrypted_98f85f8775b8_iv -in service-account.json.enc -out service-account.json -d
#  - curl https://sdk.cloud.google.com | bash > /dev/null;
#  - source $HOME/google-cloud-sdk/path.bash.inc
#  - gcloud components update kubectl
#  - gcloud auth activate-service-account --key-file service-account.json
#  - gcloud config set project lucskylab01
#  - gcloud config set compute/zone us-central1-a
#  - gcloud container cluster get-credentials lucskylab01 #(lucskylab01: cluster_name)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t lucdang/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lucdang/react-test  npm test -- --coverage

#deploy:
#  provider: script
#  script: bash ./deploy.sh
#  on:
#    branch: master
